import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//import './globals.css'
import SideBar from '@/components/SideBar'
import React from "react";
import NewChat from '@/components/NewChat';
import { getServerSession } from 'next-auth';
import { SessionProvider } from '@/components/SessionProvider';


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  {/*const session = await getServerSession{authOptions}*/}

  return (
    <html>
      <head />
      <body>
        
        {/*<SessionProvider session={session} >*/}
          <div className="flex">
            <div className="bg-[#202123] max-w-xs h-screen
            overflow-auto md:min-w-[20rem]">
            {/*side bar */}
              <SideBar />
            </div>
            {/*clientprovider - noti */}

            <div className="bg-[#343541] flex-1 inter.className">{children}</div>
          </div>
        {/*</SessionProvider>*/}
      </body>
    </html>
  )
}
export default RootLayout